add some boolean indicators for OCP
control-toolbox/CTBase.jl pull request #153
Opened 2024-06-13 13:15 UTC by PierreMartinon

Hi @ocots, @jbcaillau 
I started to add a few boolean indicators for the OCP, that I originally introduced in the DOCP struct. You can find them in Model.jl

I started with
```
    has_free_initial_time::Bool
    has_free_final_time::Bool
    has_lagrange_cost::Bool
    has_mayer_cost::Bool
```

I also have a bunch of indicators and dimensions for the different kinds of constraints, that I think belong to CTBase as well. Any comments before I add them ?

```
    # OCP constraints
    # indicators
    has_control_constraints::Bool
    has_state_constraints::Bool
    has_mixed_constraints::Bool
    has_boundary_conditions::Bool
    has_variable_constraints::Bool
    has_control_box::Bool
    has_state_box::Bool
    has_variable_box::Bool

    # dimensions
    dim_control_constraints::Int64
    dim_state_constraints::Int64
    dim_mixed_constraints::Int64
    dim_path_constraints::Int64
    dim_boundary_conditions::Int64
    dim_variable_constraints::Int64
    dim_control_box::Int64
    dim_state_box::Int64
    dim_variable_box::Int64
```

2024-06-13 14:05 UTC, ocots commented
I am OK but don't forget to not use the fields but use calls to function.

2024-06-13 14:30 UTC, PierreMartinon commented
> I am OK but don't forget to not use the fields but use calls to function.

Sure, there are actually no fields for the booleans, only the functions :D
For the dimensions I may have to add the fields and set them for instance in *nlp_constraints*, but I'll add getters for them.

2024-06-14 15:54 UTC, jbcaillau commented
@PierreMartinon second thoughts: if they are more or less already present in `CTBase.jl` (some are, actually), why wouldn't we export them from`CTBase.jl` and reuse them in `CTDirect.jl`? For those being setters / getters on an `OCP`, the logical place is indeed `CTBase.jl`, while for those related to a `DOCP`, the right place is `CTDirect.jl`.

2024-06-14 16:13 UTC, PierreMartinon commented
> @PierreMartinon second thoughts: if they are more or less already present in `CTBase.jl` (some are, actually), why wouldn't we export them from`CTBase.jl` and reuse them in `CTDirect.jl`? For those being setters / getters on an `OCP`, the logical place is indeed `CTBase.jl`, while for those related to a `DOCP`, the right place is `CTDirect.jl`.

Exactly ! It just happens that most did not seem to exist in CTBase already, unless I missed them, which is possible. Tell me if you spot redundant ones in the new
```
export has_free_final_time, has_free_initial_time, has_lagrange_cost, has_mayer_cost
export dim_boundary_conditions, dim_control_constraints, dim_state_constraints, dim_variable_constraints, dim_mixed_constraints, dim_path_constraints, dim_control_box, dim_state_box, dim_variable_box
```

2024-06-14 16:18 UTC, PierreMartinon commented
@ocots @jbcaillau On a side note, are you ok with the convention to set variable_dimension to 0 for variable-independent problems ? It would simplify things a bit for me.

2024-06-14 16:19 UTC, jbcaillau commented
> @ocots @jbcaillau On a side note, are you ok with the convention to set variable_dimension to 0 for variable-independent problems ? It would simplify things a bit for me.

Yes

2024-06-14 16:20 UTC, jbcaillau commented
@PierreMartinon seems to be still WIP, so I have updated the title

2024-06-14 16:40 UTC, PierreMartinon commented
And while I'm on CTBase, do we agree to rename *OCPInit* to *OptimalControlInit* ?

2024-06-18 08:08 UTC, PierreMartinon commented
Ok, I think we can merge:
- I did not touch variable_dimension and instead kept internal dims for x,u,v in the DOCP (since we already have a separate state dimension anyway for the possible lagrange cost reformulation)
- similarly, I kept the OCPInit renaming for a future PR

2024-06-19 22:02 UTC, ocots requested changes
See comment about consistency.

2024-06-20 06:01 UTC, PierreMartinon commented on src/model.jl
@cots Indeed I missed it. You're right, the constraints dimensions are set in *nlp_constraints* since this is where the different kinds of constraints are parsed. Before I used to manually recompute the dimensions from the output of *nlp_contraints*.

The dimensions themselves are used in conjonction with the functions for the constraints, and it is pretty internal, so I think we can leave it as that, but the getters should raise an error if called before the dimensions are set, with a message telling to call *nlp_constraits* first.

Tracking the various dimensions at each *constraint!* could probably be done, but I don't really see the point right now.

2024-06-20 06:02 UTC, PierreMartinon commented on src/init.jl
Ok, I'll add it :D

2024-06-20 09:13 UTC, PierreMartinon commented on src/model.jl
Edit: erf, -1 is not compatible with *Dimension* type. Just let it be ? If you prefer I will revert to dimensions internal to *CTDirect*

2024-06-20 22:12 UTC, merged