Add change of default AD backend
control-toolbox/CTBase.jl pull request #160
Opened 2024-06-20 13:22 UTC by ocots

https://github.com/control-toolbox/CTBase.jl/issues/25

2024-06-20 13:53 UTC, gdalle commented
My apologies but that's extremely ugly :rofl: why don't you just create a `backend` kwarg that gets passed all the way down from the user-facing functions / structs to the functions actually doing the differentiation?

2024-06-20 14:00 UTC, gdalle commented
Not to mention that you might need a combination of backends: you don't necessarily want to use the same backend for `gradient` and `jacobian` for example

2024-06-20 14:00 UTC, jbcaillau requested changes

2024-06-20 14:00 UTC, jbcaillau commented on src/default.jl
@ocots please rename `__auto` as `__get_AD_backend`

2024-06-20 14:05 UTC, gdalle commented on src/default.jl
This does not address the crux of the issue: the choice backend shouldn't be a global state in the current REPL, it should be an option that the user can choose for each optimization problem

2024-06-20 21:34 UTC, merged

2024-06-21 05:54 UTC, gdalle commented on src/default.jl
I don't know how your library works so take this with a grain of salt. But my impression was that users may not call ctgradient and friends directly, but instead try to solve a generic control problem. In that case, they wouldn't be able to pass the backend kwarg to lower level functions because all they see are high level interfaces

2024-06-21 08:57 UTC, ocots commented on src/default.jl
I think we are on the same page :-)

See [here](https://github.com/control-toolbox/CTBase.jl/issues/25#issuecomment-2182318402).